services:
  postgres:
    image: 'postgres:14.8-alpine'
    container_name: 'tms-pg'
    environment:
      - 'POSTGRES_DB=taskmanagementdb'
      - 'POSTGRES_USER=devuser'
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - './pgdata:/var/lib/postgresql/data'
      - './scripts/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql'
    ports:
      - '5432:5432'
