spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanagementdb
    username: devuser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

access-token:
  ttl: 86400
