spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanagementdb
    username: devuser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

access-token:
  ttl: 86400
