CREATE TABLE accounts
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

CREATE TABLE comments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment_text TEXT                                    NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    author_id    BIGINT,
    task_id      BIGINT,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(256)                            NOT NULL,
    description TEXT                                    NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    priority    VARCHAR(255)                            NOT NULL,
    author_id   BIGINT                                  NOT NULL,
    assignee_id BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

ALTER TABLE accounts
    ADD CONSTRAINT uc_accounts_email UNIQUE (email);

ALTER TABLE comments
    ADD CONSTRAINT fk_comments_on_author FOREIGN KEY (author_id) REFERENCES accounts (id);

ALTER TABLE comments
    ADD CONSTRAINT fk_comments_on_task FOREIGN KEY (task_id) REFERENCES tasks (id);

ALTER TABLE tasks
    ADD CONSTRAINT fk_tasks_on_assignee FOREIGN KEY (assignee_id) REFERENCES accounts (id);

ALTER TABLE tasks
    ADD CONSTRAINT fk_tasks_on_author FOREIGN KEY (author_id) REFERENCES accounts (id);
